---
title: "HBV maps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Coverage of HBV vaccines by province in the Lao PDR according to LSIS-I and LSIS-II


```{r packages}

library(tidyverse)
library(sf)
library(tmap)

```




## MICS 2017



```{r data prov}

adm1_2018 <- read_sf("data/lao_bnd_admin1/lao_bnd_admin1_ngd2018.shp")
adm1_2018

data_2017 <- read.csv("data/2017_cov_bd_penta.csv", header=T, sep=";", dec = ",")
glimpse(data_2017)

```


```{r adm1}

glimpse(adm1_2018)

st_crs(adm1_2018)

```


```{r merge}

# Merge the datasets
data_2017 %>% select(prov_new, bd_p, penta1_p, penta2_p, penta3_p) -> cov_2017

cov_2017$ADM1_EN <- cov_2017$prov_new

merge(adm1_2017, cov_2017, by = "ADM1_EN") -> adm1_2018_cov

```




## Map with ggplot


```{r bd map}

adm1_2018_cov %>% 
  ggplot()+
  geom_sf(aes(fill=bd_p)) # Yeay it worked

```


```{r map}

adm1_2018_cov %>% 
  ggplot()+
  geom_sf(aes(fill=bd_p)) +
  theme_bw()# Yeay it worked

adm1_2018_cov %>% 
  ggplot()+
  geom_sf(aes(fill=penta1_p)) +
  theme_bw()

```









## Map with tmap


```{r tmap}

tm_shape(adm1_2018_cov) + tm_borders()

map_lao = tm_shape(adm1_2018_cov) + tm_polygons()

tm_shape(adm1_2018_cov) + tm_polygons(col="bd_p") + tm_borders()

```




```{r all maps}

map_lao + 
  tm_shape(adm1_2018_cov) + 
  tm_fill(col="bd_p",
          breaks=c(20,30,40,50,60,70,80,90,100),
          labels = c("20%-30%", "30%-40%", "40%-50%", "50%-60%", "60%-70%", "70%-80%", "80%-90%", "90%-100%"), 
          palette = "viridis",
          title = "HBV birth dose coverage",
          legend.position = c("left", "bottom"),
          legend.text.size = 0.7) + 
  tm_borders()+
  tm_legend(text.size=0.5) -> map1_17

map_lao + 
  tm_shape(adm1_2018_cov) + 
  tm_fill(col="penta1_p",
          breaks=c(20,30,40,50,60,70,80,90,100), 
          labels = c("20%-30%", "30%-40%", "40%-50%", "50%-60%", "60%-70%", "70%-80%", "80%-90%", "90%-100%"), 
          palette = "viridis",
          title = "Penta dose 1 coverage",
          legend.position = c("left", "bottom"),
          legend.text.size = 0.7) + 
  tm_borders()+
  tm_legend(text.size=0.5) -> map2_17

map_lao + 
  tm_shape(adm1_2018_cov) + 
  tm_fill(col="penta2_p",
          breaks=c(20,30,40,50,60,70,80,90,100), 
          labels = c("20%-30%", "30%-40%", "40%-50%", "50%-60%", "60%-70%", "70%-80%", "80%-90%", "90%-100%"), 
          palette = "viridis",
          title = "Penta dose 2 coverage",
          legend.position = c("left", "bottom"),
          legend.text.size = 0.7) + 
  tm_borders()+
  tm_legend(text.size=0.5) -> map3_17

map_lao + 
  tm_shape(adm1_2018_cov) + 
  tm_fill(col="penta3_p",
          breaks=c(20,30,40,50,60,70,80,90,100),
          labels = c("20%-30%", "30%-40%", "40%-50%", "50%-60%", "60%-70%", "70%-80%", "80%-90%", "90%-100%"), 
          palette = "viridis",
          title = "Penta dose 3 coverage",
          legend.position = c("left", "bottom"),
          legend.text.size = 0.7) + 
  tm_borders()+
  tm_layout()+
  tm_legend(text.size=0.5) -> map4_17


tmap::tmap_save(map1_17,"outputs/map1_17.png", width=7,height=12,units ="cm")
tmap::tmap_save(map2_17,"outputs/map2_17.png", width=7,height=12,units ="cm")
tmap::tmap_save(map3_17,"outputs/map3_17.png", width=7,height=12,units ="cm")
tmap::tmap_save(map4_17,"outputs/map4_17.png", width=7,height=12,units ="cm")


#tmap_arrange(map1, map2, map3, map4, nrow=1) -> map_all

#tmap::tmap_save(map_all,"outputs/map_all.png", width=20,height=10,units ="cm")

```








## MICS 2012



```{r data prov}

adm1_2013 <- read_sf("data/lao_prov_princeton/polbnda_lao.shp")
adm1_2013

## Yes, seems to be 17 provinces!!!!

adm1_2013 %>% count(nam)


data_2012 <- read.csv("data/2012_cov_bd_penta.csv", header=T, sep=";", dec = ",")
glimpse(data_2012)

```

```{r merge}

# Merge the datasets
data_2012 %>% select(prov, hepb0_p, penta_p, nam) -> cov_2012

merge(adm1_2013, cov_2012, by = "nam") -> adm1_2013_cov

adm1_2013_cov %>% count(nam)

```


```{r crs}

st_crs(adm1_2013_cov)

tm_shape(adm1_2013_cov)+tm_polygons() # seems to work


```




## Map with tmap


```{r tmap}

tm_shape(adm1_2013_cov) + tm_polygons(col="hepb0_p") + tm_borders()

```




```{r all maps}

map_lao + 
  tm_shape(adm1_2013_cov) + 
  tm_fill(col="hepb0_p",
          breaks=c(20,30,40,50,60,70,80,90,100),
          labels = c("20%-30%", "30%-40%", "40%-50%", "50%-60%", "60%-70%", "70%-80%", "80%-90%", "90%-100%"), 
          palette = "viridis",
          title = "HBV birth dose coverage",
          legend.position = c("left", "bottom"),
          legend.text.size = 0.7) + 
  tm_borders()+
  tm_legend(text.size=0.5) -> map1_2012

map_lao + 
  tm_shape(adm1_2013_cov) + 
  tm_fill(col="penta_p",
          breaks=c(20,30,40,50,60,70,80,90,100), 
          labels = c("20%-30%", "30%-40%", "40%-50%", "50%-60%", "60%-70%", "70%-80%", "80%-90%", "90%-100%"), 
          palette = "viridis",
          title = "Pentavalent vaccine coverage",
          legend.position = c("left", "bottom"),
          legend.text.size = 0.7) + 
  tm_borders()+
  tm_legend(text.size=0.5) -> map2_2012

tmap::tmap_save(map1_2012,"outputs/map1_12.png", width=7,height=12,units ="cm")
tmap::tmap_save(map2_2012,"outputs/map2_12.png", width=7,height=12,units ="cm")

```














